repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ['--line-length=120']

  - repo: local
    hooks:
      - id: export-dependencies
        name: Export Dependencies
        language: system
        pass_filenames: false
        entry: poetry export --without-hashes --output requirements.txt
        files: ^(pyproject.toml|poetry.lock)$
