version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    ports:
      - "9200:9200"

  postgres:
    image: postgres:13
    env_file:
      - "./.env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    build: .
    env_file:
      - "./.env"
    depends_on:
      - postgres
      - elasticsearch

volumes:
  postgres_data:
